/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.duoc.hoystmarkplanet.Views.img;

import cl.duoc.hoystmarkplanet.DTO.PeliculaDTO;
import cl.duoc.hoystmarkplanet.Service.iPelicula;
import cl.duoc.hoystmarkplanet.Service.impl.PeliculaService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabia
 */
public class pEliminar extends javax.swing.JPanel {

    private static iPelicula servicio;

    public pEliminar() {
        initComponents();

        if (servicio == null) {
            this.servicio = new PeliculaService();
        }
        agregarDatos(this.servicio.listar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbTitulo = new javax.swing.JTable();
        lTitulo = new javax.swing.JLabel();
        lSubtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        bDescartar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bConfirmar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 400));
        setPreferredSize(new java.awt.Dimension(750, 400));

        tbTitulo.setAutoCreateRowSorter(true);
        tbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbTitulo);

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lTitulo.setText("Eliminar Pelicula");

        lSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        lSubtitulo.setForeground(new java.awt.Color(102, 102, 102));
        lSubtitulo.setText("Peliculas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("ID Pelicula");

        tTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tTitulo.setForeground(new java.awt.Color(153, 153, 153));
        tTitulo.setText("Ingrese ID...");
        tTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tTituloFocusLost(evt);
            }
        });
        tTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTituloMouseClicked(evt);
            }
        });
        tTitulo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tTituloInputMethodTextChanged(evt);
            }
        });
        tTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTituloActionPerformed(evt);
            }
        });

        bDescartar.setBackground(new java.awt.Color(56, 14, 97));
        bDescartar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDescartar.setPreferredSize(new java.awt.Dimension(104, 35));
        bDescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDescartarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDescartarMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Limpiar");

        javax.swing.GroupLayout bDescartarLayout = new javax.swing.GroupLayout(bDescartar);
        bDescartar.setLayout(bDescartarLayout);
        bDescartarLayout.setHorizontalGroup(
            bDescartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDescartarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        bDescartarLayout.setVerticalGroup(
            bDescartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bDescartarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bConfirmar.setBackground(new java.awt.Color(56, 14, 97));
        bConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConfirmarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bConfirmarMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Confirmar");

        javax.swing.GroupLayout bConfirmarLayout = new javax.swing.GroupLayout(bConfirmar);
        bConfirmar.setLayout(bConfirmarLayout);
        bConfirmarLayout.setHorizontalGroup(
            bConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bConfirmarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bConfirmarLayout.setVerticalGroup(
            bConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bConfirmarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSubtitulo)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tTituloInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tTituloInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloInputMethodTextChanged

    private void tTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloMouseClicked

    private void tTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloActionPerformed

    private void tTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTituloFocusGained
        // TODO add your handling code here:
        if (tTitulo.getText().equals("Ingrese ID...")) {
            tTitulo.setText("");
        }
    }//GEN-LAST:event_tTituloFocusGained

    private void tTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTituloFocusLost
        // TODO add your handling code here:
        if (tTitulo.getText().isEmpty()) {
            tTitulo.setText("Ingrese ID...");
        }
    }//GEN-LAST:event_tTituloFocusLost

    private void bDescartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDescartarMouseExited
        // TODO add your handling code here:
        bDescartar.setBackground(new java.awt.Color(56, 14, 97));
    }//GEN-LAST:event_bDescartarMouseExited

    private void bDescartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDescartarMouseClicked
        // TODO add your handling code here:
        bDescartar.setBackground(new java.awt.Color(42, 10, 73));
        tTitulo.setText("");
    }//GEN-LAST:event_bDescartarMouseClicked

    private void bConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmarMouseClicked
        // TODO add your handling code here:
        bConfirmar.setBackground(new java.awt.Color(42, 10, 73));
        try {
            servicio.eliminar(tTitulo.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        agregarDatos(servicio.listar());
    }//GEN-LAST:event_bConfirmarMouseClicked

    private void bConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmarMouseExited
        // TODO add your handling code here:
        bConfirmar.setBackground(new java.awt.Color(56, 14, 97));
    }//GEN-LAST:event_bConfirmarMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bConfirmar;
    private javax.swing.JPanel bDescartar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lSubtitulo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tTitulo;
    private javax.swing.JTable tbTitulo;
    // End of variables declaration//GEN-END:variables

    private void agregarDatos(List<PeliculaDTO> lista) {
        tbTitulo.selectAll();
        tbTitulo.clearSelection();
        DefaultTableModel modelo = (DefaultTableModel) tbTitulo.getModel();
        modelo.setRowCount(0);

        for (PeliculaDTO p : lista) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getTitulo()});
        }
    }
}
