/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.duoc.hoystmarkplanet.Views.img;

import cl.duoc.hoystmarkplanet.DTO.PeliculaDTO;
import cl.duoc.hoystmarkplanet.Service.iPelicula;
import cl.duoc.hoystmarkplanet.Service.impl.PeliculaService;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabia
 */
public class pModificar extends javax.swing.JPanel {

    private static iPelicula servicio;

    public pModificar() {
        initComponents();

        if (servicio == null) {
            this.servicio = new PeliculaService();
        }
        agregarDatos(this.servicio.listar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTitulo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        bDescartar2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bConfirmar2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Modificar Pelicula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Peliculas");

        tbTitulo.setAutoCreateRowSorter(true);
        tbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbTitulo);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("ID Pelicula");

        tId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tId.setForeground(new java.awt.Color(153, 153, 153));
        tId.setText("Ingrese ID...");
        tId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tIdFocusLost(evt);
            }
        });
        tId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tIdMouseClicked(evt);
            }
        });
        tId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tIdInputMethodTextChanged(evt);
            }
        });
        tId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdActionPerformed(evt);
            }
        });

        bDescartar2.setBackground(new java.awt.Color(56, 14, 97));
        bDescartar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDescartar2.setPreferredSize(new java.awt.Dimension(104, 35));
        bDescartar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDescartar2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDescartar2MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Limpiar");

        javax.swing.GroupLayout bDescartar2Layout = new javax.swing.GroupLayout(bDescartar2);
        bDescartar2.setLayout(bDescartar2Layout);
        bDescartar2Layout.setHorizontalGroup(
            bDescartar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDescartar2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        bDescartar2Layout.setVerticalGroup(
            bDescartar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bDescartar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bConfirmar2.setBackground(new java.awt.Color(56, 14, 97));
        bConfirmar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConfirmar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConfirmar2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bConfirmar2MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Confirmar");

        javax.swing.GroupLayout bConfirmar2Layout = new javax.swing.GroupLayout(bConfirmar2);
        bConfirmar2.setLayout(bConfirmar2Layout);
        bConfirmar2Layout.setHorizontalGroup(
            bConfirmar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bConfirmar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bConfirmar2Layout.setVerticalGroup(
            bConfirmar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bConfirmar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bDescartar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(bConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDescartar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmar2MouseExited
        // TODO add your handling code here:
        bConfirmar2.setBackground(new java.awt.Color(56, 14, 97));
    }//GEN-LAST:event_bConfirmar2MouseExited

    private void bConfirmar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmar2MouseClicked
        // TODO add your handling code here:
        bConfirmar2.setBackground(new java.awt.Color(42, 10, 73));
        String id = null;

        try {
            id = tId.getText();
            mostrarPanel(new pModificar2(id));
        } catch (Exception ex) {
            System.out.println("Error" + ex);
            JOptionPane.showMessageDialog(null, "Pelicula no encontrada.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bConfirmar2MouseClicked

    private void bDescartar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDescartar2MouseExited
        // TODO add your handling code here:
        bDescartar2.setBackground(new java.awt.Color(56, 14, 97));
    }//GEN-LAST:event_bDescartar2MouseExited

    private void bDescartar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDescartar2MouseClicked
        // TODO add your handling code here:
        bDescartar2.setBackground(new java.awt.Color(42, 10, 73));
        tId.setText("");
    }//GEN-LAST:event_bDescartar2MouseClicked

    private void tIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdActionPerformed

    private void tIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tIdInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdInputMethodTextChanged

    private void tIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tIdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdMouseClicked

    private void tIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIdFocusLost
        // TODO add your handling code here:
        if (tId.getText().isEmpty()) {
            tId.setText("Ingrese ID...");
        }
    }//GEN-LAST:event_tIdFocusLost

    private void tIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIdFocusGained
        // TODO add your handling code here:
        if (tId.getText().equals("Ingrese ID...")) {
            tId.setText("");
        }
    }//GEN-LAST:event_tIdFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bConfirmar2;
    private javax.swing.JPanel bDescartar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tId;
    private javax.swing.JTable tbTitulo;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanel(JPanel p) {
        p.setSize(750, 400);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    private void agregarDatos(List<PeliculaDTO> lista) {
        tbTitulo.selectAll();
        tbTitulo.clearSelection();
        DefaultTableModel modelo = (DefaultTableModel) tbTitulo.getModel();

        for (PeliculaDTO p : lista) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getTitulo()});
        }
    }
}
