/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2131_E2 IDENTIFIED BY "MDY2131.evaluacion_E2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_E2 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY2131_E2;
GRANT "RESOURCE" TO MDY2131_E2;
ALTER USER MDY2131_E2 DEFAULT ROLE "RESOURCE";