-- Eliminar Usuarios
DROP USER MDY2131_U1 CASCADE;
DROP USER MDY2131_U2 CASCADE;
DROP USER FINANZAS_ANALITICAS CASCADE;

--Crear Usuarios.
    -- U1
CREATE USER MDY2131_U1 IDENTIFIED BY "MDY2131.practica_U1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_U1 QUOTA UNLIMITED ON DATA;
    ----
    -- U2
CREATE USER MDY2131_U2 IDENTIFIED BY "MDY2131.practica_U2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_U2 QUOTA UNLIMITED ON DATA;
    ----
    -- U3
CREATE USER FINANZAS_ANALITICAS IDENTIFIED BY "FINANZAS.analiticas_U3"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER FINANZAS_ANALITICAS QUOTA UNLIMITED ON DATA;
    ----
-- Sesion de usuarios.
GRANT CREATE SESSION TO MDY2131_U1; -- U1
GRANT CREATE SESSION TO MDY2131_U2; -- U2
GRANT CREATE SESSION TO FINANZAS_ANALITICAS; -- U3

-- Acciones de los usuarios.
    -- U1
GRANT CREATE TABLE TO MDY2131_U1;
GRANT ALTER ANY TABLE TO MDY2131_U1;
GRANT DROP ANY TABLE TO MDY2131_U1;
GRANT CREATE PUBLIC SYNONYM TO MDY2131_U1;
GRANT CREATE SYNONYM TO MDY2131_U1;
GRANT CREATE SEQUENCE TO MDY2131_U1;
GRANT CREATE TRIGGER TO MDY2131_U1;
GRANT CREATE PROCEDURE TO MDY2131_U1;
    ----
    -- U2
GRANT CREATE VIEW TO MDY2131_U2;
    ----
    -- U3
GRANT CREATE VIEW TO FINANZAS_ANALITICAS;

-- Creando "rol_consulta"
CREATE ROLE rol_consulta;
GRANT CREATE PROCEDURE TO rol_consulta;
GRANT CREATE ANY INDEX TO rol_consulta;
    ----
-- Crear Perfil
CREATE PROFILE profile_externos
    LIMIT
        SESSIONS_PER_USER 3
        CONNECT_TIME 30
        IDLE_TIME 20
        FAILED_LOGIN_ATTEMPTS 3
        PASSWORD_LOCK_TIME 2
;

-- Asignando perfil
ALTER USER finanzas_analiticas PROFILE profile_externos; -- U3