/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2131_E1 IDENTIFIED BY "MDY2131.evaluacion_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_E1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY2131_E1;
GRANT "RESOURCE" TO MDY2131_E1;
ALTER USER MDY2131_E1 DEFAULT ROLE "RESOURCE";