DROP USER MDY2131_ET_FB CASCADE;
DROP USER MDY2131_ET_FB_DES CASCADE;
DROP USER MDY2131_ET_FB_CON CASCADE;
-- Creacion de usuarios
    --
CREATE USER MDY2131_ET_FB IDENTIFIED BY "9Aa$Vb8xC#3z"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_ET_FB QUOTA UNLIMITED ON DATA;
    --
CREATE USER MDY2131_ET_FB_DES IDENTIFIED BY "P#7qRz!9sFv2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_ET_FB_DES QUOTA UNLIMITED ON DATA;
    --
CREATE USER MDY2131_ET_FB_CON IDENTIFIED BY "L@5jNc#2oRf9"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY2131_ET_FB_CON QUOTA UNLIMITED ON DATA;
    --

-- Asignación de permisos
    -- Usuario 1
GRANT CREATE SESSION TO MDY2131_ET_FB;
GRANT CREATE TABLE TO MDY2131_ET_FB;
GRANT ALTER ANY TABLE TO MDY2131_ET_FB;
GRANT DROP ANY TABLE TO MDY2131_ET_FB;
GRANT CREATE SEQUENCE TO MDY2131_ET_FB;
GRANT CREATE ANY INDEX TO MDY2131_ET_FB;
GRANT CREATE PUBLIC SYNONYM TO MDY2131_ET_FB;
GRANT CREATE SYNONYM TO MDY2131_ET_FB;
GRANT DROP ANY SYNONYM TO MDY2131_ET_FB;
GRANT DROP PUBLIC SYNONYM TO MDY2131_ET_FB;
    -- Usuario 2
GRANT CREATE SESSION TO MDY2131_ET_FB_DES;
GRANT CREATE PROCEDURE TO MDY2131_ET_FB_DES;
GRANT CREATE TRIGGER TO MDY2131_ET_FB_DES;
GRANT CREATE VIEW TO MDY2131_ET_FB_DES;
GRANT CREATE MATERIALIZED VIEW TO MDY2131_ET_FB_DES;
    -- Usuario 3
GRANT CREATE SESSION TO MDY2131_ET_FB_CON;
