-- Uso del AVG, MAX, MIN y SUM
SELECT
    ROUND(AVG(salario)) AS "SALARIO PROMEDIO"
    ,ROUND(AVG(NVL(salario,0))) AS "SALARIO PROMEDIO CON NULOS CONSIDERADOS"
    ,MAX(salario) AS "SALARIO MAXIMO"
    ,MIN(salario) AS "SALARIO MINIMO"
    ,SUM(salario) AS "SUMATORIA DE LOS SALARIOS"
    ,MIN(fecha_contrato) AS "FECHA MAS ANTIGUA"
    ,MIN(nombre) AS "NOMBRE MIN"
    ,MAX(nombre) AS "NOMBRE MAX"
FROM
    empleado
;

-- Uso del COUNT
SELECT
    COUNT(*) AS "CANTIDAD DE EMPLEADOS"
    ,COUNT(run_jefe) AS "EMPLEADOS QUE POSEEN JEFE"
FROM
    empleado
;

-- Grupo de datos
SELECT
    CASE id_escolaridad
        WHEN 10 THEN 'BÁSICA'
        WHEN 20 THEN 'MEDIA CIENTÍFICA HUMANISTA'
        WHEN 30 THEN 'MEDIA TÉCNICO PROFESIONAL'
        WHEN 40 THEN 'SUPERIOR CENTRO DE FORMACIÓN TÉCNICA'
        WHEN 50 THEN 'SUPERIOR INSTITUTO PROFESIONAL'
        WHEN 60 THEN 'SUPERIOR UNIVERSIDAD' 
    END
        AS "ESCOLARIDAD"
    ,ROUND(AVG(salario)) AS "SALARIO PROMEDIO POR ESCOLARIDAD"
FROM
    empleado
GROUP BY
    id_escolaridad
ORDER BY
    "SALARIO PROMEDIO POR ESCOLARIDAD"
;